Select * from customer

-- Q1. What is the total revenue generated by male and female customers?

Select gender, sum(purchase_amount) as Total_revenue
from customer
group by gender

-- Q2. Which customers used a discount but still spent more than the average value?

Select Customer_id, discount_applied, purchase_amount
from customer
where discount_applied = 'Yes' 
and purchase_amount > (Select Avg(purchase_amount) from customer)

-- Q3. Which are the top 5 products with the highest average review rating?

Select item_purchased, ROUND(AVG(review_rating)::numeric, 2) as Avg_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

-- Q4. Compare the average Purchase amounts between Standard & Express Shipping

Select shipping_type, round(Avg(purchase_amount)::numeric,2) as Avg_pur_amt
from Customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? Compare average spend & total revenue b/w 
-- subscribers and non-subscribers.

Select subscription_status, 
count(customer_id) as Total_Customers,
round(avg(purchase_amount)::numeric,2) as Avg_pur_amt, 
sum(purchase_amount) as Total_Rev
from customer
group by subscription_status
order by Avg_pur_amt, Total_Rev desc;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    category,
    ROUND(
        (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)::numeric 
        / COUNT(*) * 100), 
    2) AS disc_rate
FROM customer
GROUP BY item_purchased, category
ORDER BY disc_rate DESC
LIMIT 5;

-- Q7. Segment customers into New,Returning and loyal based on their total
-- number of previous purchases, and show the count of each segment.

with customer_type as (
Select customer_id,previous_purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
Else 'Loyal'
end as Customer_segment
from Customer
)

Select Customer_segment,
count(*) as Number_of_Customers
from customer_type
group by 1
order by Number_of_Customers desc;

-- Q8. What are the top 3 most purchased products within each category

Select * from (
Select
category,
item_purchased,
count(customer_id) as Total_orders,
row_number() over(partition by category order by count(customer_id) desc) as Rn
from customer
group by category, item_purchased
) ranked
where Rn <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 repeat purchases) 
-- are likely to subscribe?

Select subscription_status,
count(customer_id) as total_customers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?

Select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;









